#
# Spring Boot configuration
#  - options: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-docs/src/main/asciidoc/appendix-application-properties.adoc
#

server:
  address: 127.0.0.1
  port: 4080

spring:

  resources:
    chain:
      cache: true
      html-application-cache: true
      strategy:
        content:
          enabled: true
          paths: /css/**, /images/**, /js/**

  thymeleaf:
    mode: LEGACYHTML5
